sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - mvn clean install
before_install:
  - openssl aes-256-cbc -K $encrypted_177f44202b14_key -iv $encrypted_177f44202b14_iv -in googlegcpaccount.json.enc -out googlegcpaccount.json -d
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file googlegcpaccount.json
  - gcloud config set project abstract-dragon-284619
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-1
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t hcm-service:$SHA .
  - docker tag hcm-service:$SHA jbuilder1993/hcm-service:$SHA
  - docker push jbuilder1993/hcm-service:$SHA
  - docker build -f Dockerfile -t hcm-service .
  - docker tag hcm-service jbuilder1993/hcm-service
  - docker push jbuilder1993/hcm-service
  - kubectl apply -f k8s
  - kubectl set image deployment/users-deployment users=jbuilder1993/hcm-service:$SHA
