sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - mvn clean install
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t hcm-service:$SHA .
  - docker tag hcm-service:$SHA jbuilder1993/hcm-service:$SHA
  - docker push jbuilder1993/hcm-service:$SHA
  - docker build -f Dockerfile -t hcm-service .
  - docker tag hcm-service jbuilder1993/hcm-service
  - docker push jbuilder1993/hcm-service
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main

