apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: workpower
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: initdb
        configMap:
          name: mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  initdb.sql: |
    use workpower;
    CREATE TABLE workpower.USERS (ID INT PRIMARY KEY, NAME VARCHAR(45), EMAILID VARCHAR(255));
    INSERT INTO workpower.USERS (ID, NAME, EMAILID) VALUES (1, 'Jie Liu','jbuilder1993@gmail.com');
    INSERT INTO workpower.USERS (ID, NAME, EMAILID) VALUES (2, 'Xiao Ying Li','mike_daniel@yahoo.co.in');
    INSERT INTO workpower.USERS (ID, NAME, EMAILID) VALUES (3, 'David Lawrance','david_law@gmail.com');
    INSERT INTO workpower.USERS (ID, NAME, EMAILID) VALUES (4, 'Cjang yu Liu','david_law@gmail.com');
