apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress-service
  annotations:
    dev.okteto.com/generate-host: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-ip-service
                port: 
                  number: 9888
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user2-ip-service
                port:
                  number: 8080
          - path: /oauth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: oauth-service
                port: 
                  number: 5000
          - path: /employee(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: employee-service
                port: 
                  number: 3000                                      
