apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /users
            backend:
              serviceName: user-ip-service
              servicePort: 9888
          - path: /user
            backend:
              serviceName: user2-ip-service
              servicePort: 8080             